services:
    navidrome-downloader:
#      image: ghcr.io/yeounhyeok/navidrome-auto-downloader-gui:latest
      build: .
      container_name: navidrome-downloader
      ports:
        - "5000:5000"
      volumes:
        - ./testmusics:/music
      # Load environment variables from .env file
      env_file:
        - .env
      restart: unless-stopped