services:
    navidrome-downloader:
      build:
        context: .
        dockerfile: Dockerfile
      image: ghcr.io/yeounhyeok/navidrome-auto-downloader-gui:latest
      container_name: navidrome-downloader
      ports:
        - "5000:5000"
      volumes:
        - ./music:/music
        #- ./download_music.sh:/app/download_music.sh
      # Load environment variables from .env file
      env_file:
        - .env
      restart: unless-stopped